# Generated by Django 3.2 on 2021-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210513_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
