# Generated by Django 3.2 on 2021-05-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210513_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Set Address', max_length=200),
        ),
    ]
