# Generated by Django 3.2 on 2021-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='curbside',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
