# Generated by Django 3.2 on 2021-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_curbside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
