# Generated by Django 3.2 on 2021-05-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20210513_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image10',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
